'use client';
/** Admin Posts CRUD - supports image upload to Supabase Storage 'posts' bucket */
import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabaseClient';
export default function AdminPosts() {
  const [posts,setPosts]=useState<any[]>([]); const [title,setTitle]=useState(''); const [excerpt,setExcerpt]=useState(''); const [content,setContent]=useState(''); const [file,setFile]=useState<File|null>(null); const [loading,setLoading]=useState(false);
  useEffect(()=>{ fetchPosts(); },[]);
  async function fetchPosts(){ const { data } = await supabase.from('posts').select('*').order('created_at'); setPosts(data||[]); }
  async function uploadAndCreate(){ setLoading(true); let coverPath=null; if(file){ const fileName=`${Date.now()}_${file.name}`; const { error: upErr } = await supabase.storage.from('posts').upload(fileName, file); if(upErr){ alert(upErr.message); setLoading(false); return; } coverPath=`posts/${fileName}`; } const { error } = await supabase.from('posts').insert([{ title, excerpt, content, cover_image: coverPath }]); if(error) alert(error.message); else { setTitle(''); setExcerpt(''); setContent(''); setFile(null); fetchPosts(); } setLoading(false); }
  async function deletePost(id:string){ if(!confirm('Delete post?')) return; const { error } = await supabase.from('posts').delete().eq('id', id); if(error) alert(error.message); else fetchPosts(); }
  return (<div className="p-6"><h2 className="text-xl font-semibold mb-4">Posts</h2><div className="mb-4 space-y-2"><input placeholder="Title" value={title} onChange={(e)=>setTitle(e.target.value)} className="p-2 bg-slate-800 rounded w-full" /><input placeholder="Excerpt" value={excerpt} onChange={(e)=>setExcerpt(e.target.value)} className="p-2 bg-slate-800 rounded w-full" /><textarea placeholder="Content" value={content} onChange={(e)=>setContent(e.target.value)} className="p-2 bg-slate-800 rounded w-full" /><div className="mt-2"><label className="block text-sm mb-1">Cover image (optional)</label><input type="file" onChange={(e)=> setFile(e.target.files?e.target.files[0]:null)} /></div><button onClick={uploadAndCreate} className="px-4 py-2 bg-amber-500 rounded" disabled={loading}>Create Post</button></div><div className="grid gap-3">{posts.map(p=>(<div key={p.id} className="p-3 bg-slate-800 rounded flex justify-between items-center"><div><div className="font-semibold">{p.title}</div><div className="text-sm text-slate-400">{p.excerpt}</div></div><div className="flex gap-2"><button onClick={()=>deletePost(p.id)} className="px-3 py-1 bg-red-600 rounded">Delete</button></div></div>))}</div></div>);
}
